# Generated by Django 3.0.2 on 2020-02-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_personalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='address',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='date_of_birth',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='mobile',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='nationality',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='religion',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
